### ISSUE TITLE
Improve the styling of the app

### ISSUE THREAD

**Issue by nirajacharyaa** [nirajacharyaa/musify#1]
Improve some styling of the app. Write a proper description of your changes and upload a screenshot of the app after your changes to the PR description.

**Comment by falguni-k** [comment]
Hi! I would like to work on this. Please assign it to me.
Thanks

**Comment by nirajacharyaa** [comment]
You can just make a PR without asking for an assignment.

**Comment by AdheelAhmed-D3CD** [comment]
Cool I will also do my best

**Comment by falguni-k** [comment]
Raised the PR....
