### ISSUE TITLE
Make the song list responsive.

### ISSUE THREAD

**Issue by nirajacharyaa** [nirajacharyaa/musify#11]
The song list break the app in mobile view, so make sure the list stays below the navigation button in mobile view, or for the width below which the list won't fit in the side.

**Comment by IAmTamal** [comment]
Can i be assigned with this issue sir ?

**Comment by Atharv777** [comment]
@nirajacharyaa please assign me

**Comment by nirajacharyaa** [comment]
Go on. Please read `CONTRIBUTING.md` before making a PR.

**Comment by nirajacharyaa** [comment]
@Atharv777 Make a PR you don't need to be assigned for making a PR, even if I don't merge yours or his' I will make sure that PR counts to Hacktoberfest adding `hacktoberfest-accepted` label.

**Comment by Atharv777** [comment]
Please merge my PR #12

**Comment by nirajacharyaa** [comment]
@IAmTamal It's still breaking, you can work on it to make it working.

![image](https://user-images.githubusercontent.com/54741119/135703302-f357f442-250d-4c13-ab2d-a8a58d8fae54.png)

**Comment by IAmTamal** [comment]
@nirajacharyaa  sir i have updated the files. Instead of clicking on inspect, please use your mobile device to confirm the responsiveness because of a github glitch. 

If the PR is okay please do accept it. 
Thankyou.
