### ISSUE TITLE
Adding a Random song button

### ISSUE THREAD

**Issue by Tejasvigupta** [nirajacharyaa/musify#2]
It would be nice to have a button to shuffle the playlist.

**Comment by nirajacharyaa** [comment]
Good Idea, You can do it.

**Comment by Tejasvigupta** [comment]
Assign the hacktoberfest tag and I will be good to go. @nirajacharyaa

**Comment by nirajacharyaa** [comment]
You may proceed.

**Comment by Tejasvigupta** [comment]
#9 PR for this issue.

**Comment by nirajacharyaa** [comment]
Merged it in a separate branch, because I was not running a deployment build on this project. I will check and see if I will merge it in main. Thanks for contributing and happy hacktoberfest. Don't forget to star the project.
