### ISSUE TITLE
Want to change the cover image of the song number 2.

### ISSUE THREAD

**Issue by 07tAnYa** [nirajacharyaa/musify#25]
Want to change the cover image of the song number 2 as both the cover pages of song number 2 and 3 are same.

![Screenshot 2023-08-19 112420](https://github.com/nirajacharyaa/musify/assets/140234197/8b2f3156-9d1a-441e-aaa8-692da6e55f96)
![Screenshot 2023-08-19 112614](https://github.com/nirajacharyaa/musify/assets/140234197/04b1ab68-e399-4110-96a0-364c91537492)

**Comment by nirajacharyaa** [comment]
That's an album cover they are from same album, may be add some more songs, some songs of Taylor Swift would be awesome.

**Comment by 07tAnYa** [comment]
Sir I have sent a PR kindly visit that n merge it too.
