### ISSUE TITLE
Can I add a list displaying all the songs

### ISSUE THREAD

**Issue by Atharv777** [nirajacharyaa/musify#3]

**Comment by nirajacharyaa** [comment]
Yes, feel free to do that. Read `CONTRIBUTING.md` before making a PR.

**Comment by Atharv777** [comment]
I have created a PR, please merge it #6

**Comment by nirajacharyaa** [comment]
I merged it. It looked fine on desktop but breaks on mobile. I am opening another issue for that. Your PR will be counted in Hacktoberfest, keep contributing to the Open Source. Don't forget to star the project. thank you.

**Comment by Atharv777** [comment]
Please attach a screenshot too in that issue, I am a begginer in open source please tell me If I fix that issue then will that PR be counted as it is on same project?

**Comment by nirajacharyaa** [comment]
Yes, every Pull request counts separately. I have opened an issue once you fix it reply to that issue, I will assign it to you and create a PR after that. You just need to push the list below the navigation buttons.

![image](https://user-images.githubusercontent.com/54741119/135702728-926f0ff6-3e70-47fe-a53d-2012076ab9b0.png)

**Comment by nirajacharyaa** [comment]
Please make sure that everything is working once you fix it and attach a screenshot to the PR as I am not running automatic check and deployment, things may break because it's hard for me to check.
