### ISSUE TITLE
Missing Footer (information about website)

### ISSUE THREAD

**Issue by NKkrisz** [nirajacharyaa/musify#7]
Hello, I would like to contribute by making a footer with some links to this project (Github link to this project for example)!

**Comment by NKkrisz** [comment]
Made a pull request :)

**Comment by nirajacharyaa** [comment]
Your changes were reverted because they were breaking the code, but I made sure that this will count in Hacktoberfest. Keep contributing. Thanks. Don't forget to Star the project.
